import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { IoSearch } from "react-icons/io5";
import Link from "next/link";
import { IoCartOutline } from "react-icons/io5";
import { CgProfile } from "react-icons/cg";
import { FaLinkedin } from "react-icons/fa";
import { FaSquareFacebook } from "react-icons/fa6";
import { FaInstagram } from "react-icons/fa";
import { FaSkype } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import { FaPinterest } from "react-icons/fa";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <header>
          <nav>
            <div className="w-screen h-24">
              <div className="w-screen flex justify-between items-center h-12 ">

                <div><IoSearch className="text-xl ml-5 "/></div>

                <div><h2 className=" text-2xl ">Avion</h2></div>

                <div className="flex w-20 justify-around text-xl mr-4 ">
                  <IoCartOutline className=""/>
                  <CgProfile className=""/>
                </div>
                
              </div>
              <hr />


              <div className="w-screen h-12 " >
                <ul className="flex gap-16 text-slate-500 pt-2.5 justify-center">
                  <li><Link href='/plant_pots'>Plant Pots</Link></li>
                  <li><Link href='/ceramics'>Ceramics</Link></li>
                  <li><Link href='/tables'>Tables</Link></li>
                  <li><Link href='/chairs'>Chairs</Link></li>
                  <li><Link href='/crockery'>Crockery</Link></li>
                  <li><Link href='/tablewear'>Tablewear</Link></li>
                  <li><Link href='/cutlery'>Cutlery</Link></li>
                </ul>
              </div>
            </div>


          </nav>
        </header>


        <main className="flex-1">
          {children}
        </main>


        <footer className="">

          <div className="w-[100vw] h-[440px] flex items-center justify-center bg-customBrown">

            <div className=" flex flex-col text-white items-center w-[50vw] h-80 bg-customBrown gap-y-12">

              <div><h2 className="text-4xl ">Join the club and get the benefits</h2></div>

              <div className="mx-64"><p className="text-2xl text-center">Sign up for our newsletter and receive exclusive offers on new ranges, sales, pop up stores and more</p></div>

              <div>
                <ul className="flex gap-x-4">
                  <li><input type='checkbox' name="offers" /> Exclusive offers</li>
                  <li> <input type="checkbox" name="free_events" /> Free events</li>
                  <li> <input type="checkbox" name="discounts" /> Large discounts</li>
                </ul>
              </div>

              <div className="flex">
                <div><input type="email" name="email" className="w-96 h-14"/></div>
                <div><button type="button" className="h-14 w-36 bg-customBlue">Sign up</button></div>
              </div>

            </div>

          </div>




          <div className="w-screen h-[400px] flex bg-slate-400">
            <div className="w-[17vw] h-[1440] bg-customBlue">
              <ul className="flex flex-col text-white relative top-14 left-24 gap-4 ">
                <li className="text-lg">Menu</li>
                <li>New arrivals</li>
                <li>Best sellers</li>
                <li>Recently viewed</li>
                <li>Popular this week</li>
                <li>All products</li>
              </ul>
            </div>

            <div className="w-[17vw] h-[1440] bg-customBlue">
              <ul className="flex flex-col text-white relative top-14 left-24 gap-4 ">
                <li className="text-lg">Categories</li>
                <li>Crockery</li>
                <li>Furniture</li>
                <li>Homeware</li>
                <li>Plant pots</li>
                <li>Chairs</li>
                <li>Crockery</li>
              </ul>
            </div>


            <div className="w-[17vw] h-[1440] bg-customBlue">
            <ul className="flex flex-col text-white relative top-14 left-24 gap-4 ">
              <li className="text-lg">Our company</li>
              <li>About us</li>
              <li>Vacancies</li>
              <li>Contact us</li>
              <li>Privacy</li>
              <li>Returns policy</li>
            </ul>
            </div>



            <div className="w-[49vw] h-[1440] bg-customBlue">
              <ul className="flex flex-col text-white relative top-14 left-28 gap-4 ">
                <li className="text-lg">Join our mailing list</li>
              </ul>
              <div className="relative top-20 left-28">
                <input type="text" name="mail" className="w-[500px] h-[56px] bg-customPurple text-white"  placeholder="your@email.com"/>
                <button className="w-[130px] h-[56px] bg-white">Sign up</button>
              </div>

            </div>
          </div>
          <hr />
          <div className="w-screen h-12 bg-customBlue flex justify-between items-center text-white">
              <div className="ml-24"><p className="text-base">Copyright 2022 Avion LTD</p></div>

              <div className="mr-24">
                <ul className="flex gap-8 text-2xl">
                  <li><Link href='/linked_in'> <FaLinkedin /></Link></li>
                  <li><Link href='/facebook'><FaSquareFacebook /></Link></li>
                  <li><Link href='/instagram'><FaInstagram /></Link></li>
                  <li><Link href='/skype'><FaSkype /></Link></li>
                  <li><Link href='/twitter'><FaTwitter /></Link></li>
                  <li><Link href='/pinterest'><FaPinterest /></Link></li>
                </ul>
              </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
